[build]
  command = "npm run build"
  publish = "dist" # Change if your output directory is different
  functions = "netlify/functions"

# This ensures that function requests are properly routed
[[redirects]]
  from = "/netlify/functions/*"
  to = "/netlify/functions/:splat"
  status = 200

# This makes sure your SPA routes work correctly
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200